### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by carleshf** [ga4gh-beacon/beacon-verifier#1]
Hi! Trying to install the verifier as indicated in the `README` resulted in error in Windows 10:

```
(win10-cnag) C:\Users\Carles> cargo install beacon-verifier
    Updating crates.io index
error: could not find `beacon-verifier` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```

The solution would be to indicate to install a git repository and point to `beacon-verifier` as:

```
(win10-cnag) C:\Users\Carles> cargo install --git https://github.com/ga4gh-beacon/beacon-verifier
```

Also, indicate all system-dependencies to properly perform the installation.

**Comment by MrRobb** [comment]
Hello Carles, the first production version of the verifier will be released this Friday. `cargo install beacon-verifier` should work by then.

**Comment by carleshf** [comment]
Just so you know the `REAME` is still broken:

```bash
(imac-cnag)~ carles$ cargo install beacon-verifier
    Updating crates.io index
error: could not find `beacon-verifier` in registry `https://github.com/rust-lang/crates.io-index` with version `*`
```
