### ISSUE TITLE
External specs are not implemented

### ISSUE THREAD

**Issue by carleshf** [ga4gh-beacon/beacon-verifier#2]
Running the validator does not let clear if the result is fine or not. Although, I understand this is not the expected output, right?

```bash
(imac-cnag):~ carles$ echo $RUST_BACKTRACE
1
(imac-cnag):~ carles$ beacon-verifier http://0.0.0.0:5050
 INFO  beacon_verifier > Loading spec from: https://github.com/ga4gh-beacon/beacon-v2-Models/tree/main/BEACON-V2-draft4-Model
thread 'main' panicked at 'External specs are not implemented yet', src/spec.rs:36:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

How I can run the validator, properly, on the local running instance of beacon-v2?

**Comment by MrRobb** [comment]
Hello Carles, today I will be fixing loading the model from a URL and then it should work fine. You are not doing anything wrong, is just that the software is in active development.
